# Generated by Django 5.2.8 on 2025-11-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('has_projector', models.BooleanField(default=False)),
            ],
        ),
    ]
